### ISSUE TITLE
Add working Tower Of Doom hack plz

### ISSUE THREAD

**Issue by Staraner** [Kxinghello/blooket-hack#7]

**Comment by GlixzzyBlooketHacks** [comment]
> _No description provided._

head to my blooket hacks all work recent updates are uploaded https://github.com/GlixzzyBlooketHacks/Glixzzy.github.io. any complains or issues file one all m hacks work

**Comment by ZasticBradyn** [comment]
> > _No description provided._
> 
> head to my blooket hacks all work recent updates are uploaded https://github.com/GlixzzyBlooketHacks/Glixzzy.github.io. any complains or issues file one all m hacks work

hello gliz
